Jc/i18n zh tw
Turing-Chain/certs.turingchain.tech pull request #64
Opened 2022-06-14 06:59 UTC by paul71633

finished all required i18n for Chinese

2022-06-15 09:53 UTC, TseHang commented
一瞬間就加了，最後選用 netlify 嗎？ cool 🎉

2022-06-15 09:56 UTC, TseHang reviewed
1. PR title 是不是要改一下 😂
2. 這個按鈕圖案有想要換一下嗎？ cc @FuuuYunnn 
![截圖 2022-06-15 下午5 55 37](https://user-images.githubusercontent.com/14778824/173799853-52f017bd-70e8-4684-b058-76d15c8d1720.png)

2022-06-17 07:37 UTC, paul71633 commented
> * PR title 是不是要改一下 😂
> * 這個按鈕圖案有想要換一下嗎？ cc @FuuuYunnn
>   ![截圖 2022-06-15 下午5 55 37](https://user-images.githubusercontent.com/14778824/173799853-52f017bd-70e8-4684-b058-76d15c8d1720.png)



> * PR title 是不是要改一下 😂
> * 這個按鈕圖案有想要換一下嗎？ cc @FuuuYunnn
>   ![截圖 2022-06-15 下午5 55 37](https://user-images.githubusercontent.com/14778824/173799853-52f017bd-70e8-4684-b058-76d15c8d1720.png)

樣式已修改～

2022-07-07 09:53 UTC, ching56 requested changes

2022-07-07 15:09 UTC, paul71633 commented on assets/js/setup-i18n.js
> +    this.translate();
這個我再測試一下

2022-07-07 15:10 UTC, paul71633 commented on assets/js/setup-i18n.js
> +  var langString = langCookie[2];
了解，這邊我再做修改

2022-07-14 05:29 UTC, ching56 commented on assets/js/setup-i18n.js
> +    this.translate();
目前我測試沒有發現問題了！

2022-07-25 08:59 UTC, merged